# Baselines

### Setup and Imports

In [3]:
import sys
import os
import pandas as pd
import numpy as np
import json
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()

# Add paths for imports
sys.path.append('../../stage1_analysis/source_finding')
sys.path.append('../../stage1_analysis/mapping_generation')

from rag_source_finder import RAGSourceFinder
from easy_llm_importer import LLMClient

# Data path
DATA_PATH = "../../data/SCAR_cleaned_manually.csv"

### Baseline 1: Pure Embedding Retrieval (Top 3)

In [4]:
# Initialize RAG source finder
finder = RAGSourceFinder(embedding_mode="name_properties")
finder.load_corpus_from_csv(DATA_PATH)
finder.embed_corpus()

Loaded 333 unique sources from corpus (mode: name_properties)
Generating embeddings for corpus...
Generated 333 embeddings

In [5]:
# Run Baseline 1: Pure embedding retrieval with top 3
baseline1_results = finder.evaluate_on_dataset(DATA_PATH, top_k=3)
baseline1_results['baseline'] = 'embedding_top3'
baseline1_results.to_csv('baseline1_embedding_top3.csv', index=False)
print(f"Baseline 1 saved: {len(baseline1_results)} rows")
baseline1_results.head()

Evaluating on 400 examples...
Processed 10/400 examples
Processed 20/400 examples
Processed 30/400 examples
Processed 40/400 examples
Processed 50/400 examples
Processed 60/400 examples
Processed 70/400 examples
Processed 80/400 examples
Processed 90/400 examples
Processed 100/400 examples
Processed 110/400 examples
Processed 120/400 examples
Processed 130/400 examples
Processed 140/400 examples
Processed 150/400 examples
Processed 160/400 examples
Processed 170/400 examples
Processed 180/400 examples
Processed 190/400 examples
Processed 200/400 examples
Processed 210/400 examples
Processed 220/400 examples
Processed 230/400 examples
Processed 240/400 examples
Processed 250/400 examples
Processed 260/400 examples
Processed 270/400 examples
Processed 280/400 examples
Processed 290/400 examples
Processed 300/400 examples
Processed 310/400 examples
Processed 320/400 examples
Processed 330/400 examples
Processed 340/400 examples
Processed 350/400 examples
Processed 360/400 examples
Processed 370/400 examples
Processed 380/400 examples
Processed 390/400 examples
Processed 400/400 examples
Baseline 1 saved: 400 rows

,id,target,gold_source,all_golden_sources,predicted_rank_1,gold_rank,num_golden_found,found_golden_sources,golden_ranks,top_k_sources,top_k_scores,embedding_mode,query_embedding_text,target_background,target_properties,baseline
0,1,biological clock,clock,[clock],clock,1,1,[clock],[1],"[clock, Biological Evolution, Time Machine]","[0.48747001166636494, 0.4727238510932971, 0.43...",name_properties,"biological clock. changes, state, adjust",The biological clock is a fundamental aspect o...,"changes, state, adjust",embedding_top3
1,2,Biosphere,Library,[Library],Ecosystem,-1,0,[],[],"[Ecosystem, ecosystem, Biological Evolution]","[0.7417536552432331, 0.600835231456412, 0.4637...",name_properties,"Biosphere. biology, biodiversity, ecosystem",The biosphere refers to the sum of all ecosyst...,"biology, biodiversity, ecosystem",embedding_top3
2,3,Respiratory system,engine,"[engine, Air handling system, air circulation ...",respiration,-1,0,[],[],"[respiration, Human Body, the skeletal system]","[0.5764429137186268, 0.4766108890476132, 0.433...",name_properties,"Respiratory system. oxygen, the lungs, breathi...",The respiratory system is a critical biologica...,"oxygen, the lungs, breathing muscles",embedding_top3
3,4,Spread of Pathogens,Spread of Fire,[Spread of Fire],Crowd,3,1,[Spread of Fire],[3],"[Crowd, Disease, Spread of Fire]","[0.5004412128308713, 0.47933010292152944, 0.45...",name_properties,"Spread of Pathogens. pathogen, crowd, Preventi...","The spread of pathogens is a serious concern, ...","pathogen, crowd, Prevention and control measures",embedding_top3
4,5,Gene editing,kirigami,[kirigami],bacterial mutation,-1,0,[],[],"[bacterial mutation, Evolution, edit]","[0.37034962784168296, 0.3350655099294726, 0.32...",name_properties,"Gene editing. Gene, CRISPR-Cas9 Technology, ed...",Gene editing is a revolutionary technique in m...,"Gene, CRISPR-Cas9 Technology, edited gene",embedding_top3

## Baseline 2: Embedding Retrieval + LLM Selection (Top 10 → 3)

In [ ]:
# Initialize LLM client for Llama 405B
llm_client = LLMClient()

import re
import ast

# Build source properties lookup from SCAR data
df_scar = pd.read_csv(DATA_PATH)
source_properties_lookup = {}
for _, row in df_scar.iterrows():
    source_name = row['system_b']
    if source_name not in source_properties_lookup:
        source_properties_lookup[source_name] = set()
    # Extract source properties from mappings_parsed (second element of each pair)
    if pd.notna(row.get('mappings_parsed')):
        try:
            mappings = ast.literal_eval(row['mappings_parsed'])
            for pair in mappings:
                if len(pair) > 1:
                    source_properties_lookup[source_name].add(pair[1])
        except:
            pass

# Convert sets to comma-separated strings
source_properties_lookup = {k: ", ".join(sorted(v)) for k, v in source_properties_lookup.items()}

def get_source_properties(source_name):
    """Get properties for a source from lookup"""
    return source_properties_lookup.get(source_name, "")

def llm_select_sources(target_name, target_properties, candidates, llm_client, top_k=3):
    """Use Llama 405B to select best sources from candidates"""
    
    # Format candidates for prompt with properties from lookup
    candidates_text = "\n".join([
        f"{i+1}. {c.name} - {get_source_properties(c.name)}"
        for i, c in enumerate(candidates)
    ])
    
    prompt = f"""You are selecting analogous sources for a scientific analogy.

Target concept: {target_name}
Target : {target_properties}

Candidate source concepts:
{candidates_text}

Select the {top_k} BEST candidates that would make good analogies for the target concept.
Return ONLY a JSON array of the candidate numbers (1-indexed), e.g., [1, 3, 5]
Do not include any explanation, just the JSON array.
"""
    #print("prompt:\n", prompt)
    
    try:
        response = llm_client.chat(
            model_name="llama-3.1-405b-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=100
        )
        # Try to extract JSON array from response
        response_clean = response.strip()
        
        # Try direct JSON parse first
        try:
            selected = json.loads(response_clean)
        except json.JSONDecodeError:
            # Try to find array pattern in response
            match = re.search(r'\[[\d,\s]+\]', response_clean)
            if match:
                selected = json.loads(match.group())
            else:
                # Extract numbers from response
                numbers = re.findall(r'\b([1-9]|10)\b', response_clean)
                selected = [int(n) for n in numbers[:top_k]]
        
        if not selected:
            return candidates[:top_k]
            
        return [candidates[i-1] for i in selected if 1 <= i <= len(candidates)][:top_k]
    except Exception as e:
        print(f"LLM selection failed: {e}, falling back to top {top_k}")
        return candidates[:top_k]

In [ ]:
# Run Baseline 2: Embedding + LLM selection
df = pd.read_csv(DATA_PATH)
baseline2_results = []

# Helper to extract target properties from mappings_parsed
def get_target_properties(row):
    if pd.notna(row.get('mappings_parsed')):
        try:
            mappings = ast.literal_eval(row['mappings_parsed'])
            props = [pair[0] for pair in mappings if len(pair) > 0]
            return ", ".join(props)
        except:
            pass
    return ""

print(f"Running Baseline 2 on {len(df)} examples...")
for idx, row in df.iterrows():
    target_name = row['system_a']
    target_bg = row['system_a_background']
    target_properties = get_target_properties(row)
    gold_source = row['system_b']
    
    # Get top 10 from embeddings
    candidates = finder.find_source(target_name, target_bg, top_k=10)
    # LLM selects best 3
    selected = llm_select_sources(target_name, target_properties, candidates, llm_client, top_k=3)
    
    # Find gold rank in selected
    selected_names = [s.name for s in selected]
    print("target_name:\n", target_name)
    print("selected_names:\n", selected_names)
    gold_rank = -1
    for i, name in enumerate(selected_names):
        if gold_source.lower() in name.lower() or name.lower() in gold_source.lower():
            gold_rank = i + 1
            break
    
    baseline2_results.append({
        'id': row['id'],
        'target': target_name,
        'target_background': target_bg,
        'gold_source': gold_source,
        'top_10_sources': [c.name for c in candidates],
        'top_10_scores': [c.similarity_score for c in candidates],
        'llm_selected_sources': selected_names,
        'llm_selected_scores': [s.similarity_score for s in selected],
        'gold_rank': gold_rank,
        'embedding_mode': finder.embedding_mode,
        'baseline': 'embedding_llm_top10_to_3'
    })
    
    if (idx + 1) % 10 == 0:
        print(f"Processed {idx + 1}/{len(df)}")

baseline2_df = pd.DataFrame(baseline2_results)
baseline2_df.to_csv('baseline2_embedding_llm.csv', index=False)
print(f"Baseline 2 saved: {len(baseline2_df)} rows")
baseline2_df.head()

Running Baseline 2 on 400 examples...
target_name:
 biological clock
selected_names:
 ['clock', 'day and night cycle', 'Time Machine']
target_name:
 Biosphere
selected_names:
 ['Ecosystem', 'ecosystem', 'Desert']
target_name:
 Respiratory system
selected_names:
 ['Air handling system', 'air circulation ducts', 'lubrication system']
target_name:
 Spread of Pathogens
selected_names:
 ['Spread of Fire', 'Disease', 'Population Movement']
target_name:
 Gene editing
selected_names:
 ['bacterial mutation', 'edit', 'Evolution']
target_name:
 Water Cycle
selected_names:
 ['Wave Propagation', 'Water pipe system', 'Conservation of Water Flow']
target_name:
 Cell division
selected_names:
 ['program', 'Factory', 'Disassembly']
target_name:
 Origin of Life
selected_names:
 ['Evolution', 'Biological Evolution', 'bacterial mutation']
target_name:
 The Genetic Code
selected_names:
 ['Computer Code', 'Deciphering the Code', 'The Neural Network of Computers']
target_name:
 Ecosystem
selected_names:
 ['Ecosystem', 'ecosystem', 'Biological Evolution']
Processed 10/400
target_name:
 Nervous System
selected_names:
 ['The Neural Network of Computers', 'A Distributed Computing System', 'communication networks']
target_name:
 Immune System
selected_names:
 ['Human Body', 'Firewall', 'The Brain']
target_name:
 Cell Membranes
selected_names:
 ['Walls', 'The Brain', 'Mirrors']
target_name:
 Protein folding
selected_names:
 ['Origami', 'a three-dimensional puzzle', 'A Puzzle']
target_name:
 Photosynthesis
selected_names:
 ['Plants', 'Solar Panels', 'respiration']
target_name:
 Platelets
selected_names:
 ['sponge', 'Printers Print Documents', 'Healing']
target_name:
 Genome
selected_names:
 ['Computer Code', 'Operating System', 'Machines']
target_name:
 Brain
selected_names:
 ['The Brain', 'The Nervous System', 'The Neural Network of Computers']
target_name:
 Nucleus
selected_names:
 ['atom', 'Computer Processor', 'Building Structure']
target_name:
 Biological Evolution
selected_names:
 ['natural selection', 'bacterial mutation', 'Urban Evolution']
Processed 20/400
target_name:
 DNA Replication
selected_names:
 ['code', 'the replicator', 'Chemical Reactions']
target_name:
 Food Chain
selected_names:
 ['Supply Chain', 'Circular Economy', 'Factory System']
target_name:
 DNA Double Helix Structure
selected_names:
 ['The Helix Bridge', 'Building Structure', 'A Jigsaw Puzzle']
target_name:
 Food Chain
selected_names:
 ['Supply Chain', 'Circular Economy', 'Factory System']
target_name:
 Cell Signaling
selected_names:
 ['Neural Networks', 'Electronic Signal Transmission', 'Circuits']
target_name:
 Genetic Mutation
selected_names:
 ['bacterial mutation', 'Program Error', 'Circuit Malfunction']
target_name:
 DNA Sequencing
selected_names:
 ['Pedigree Trees', 'bacterial mutation', 'Crime Scene']
target_name:
 Food Chain
selected_names:
 ['Supply Chain', 'Factory', 'Cooking']
target_name:
 eye
selected_names:
 ['blind', 'Blindness', 'eating dinner']
target_name:
 The Process of History
selected_names:
 ['Foundation Series', 'A Jigsaw Puzzle', 'Computer']
Processed 30/400
target_name:
 Gene Mutation
selected_names:
 ['bacterial mutation', 'Program Error', 'Evolution']
target_name:
 Cell Signaling
selected_names:
 ['signal', 'Neural Networks', 'Electronic Signal Transmission']
target_name:
 Synaptic transmission between neurons
selected_names:
 ['Neural Networks', 'Electronic Signal Transmission', 'Information Flow']
target_name:
 Cell division
selected_names:
 ['program', 'Factory', 'Disassembly']
target_name:
 Nucleus
selected_names:
 ['atom', 'A Distributed Computing System', 'Building Structure']
target_name:
 Photosynthesis
selected_names:
 ['Plants', 'Solar Panels', 'Greenhouses']
target_name:
 Water Cycle
selected_names:
 ['Water pipe system', 'River', 'Vortex']
target_name:
 Land System
selected_names:
 ['Skin System', 'Tree', 'ecosystem']
target_name:
 Earth
selected_names:
 ['planet', 'Ecosystem', 'Greenhouse']
target_name:
 Natural Disasters
selected_names:
 ['natural selection', 'Dust Storm', 'Building Repair']
Processed 40/400
target_name:
 Musculoskeletal system
selected_names:
 ['the skeletal system', 'Human Body', 'Human Hands']
target_name:
 Respiratory system
selected_names:
 ['Air handling system', 'air circulation ducts', 'lubrication system']
target_name:
 Microbiome
selected_names:
 ['Disease', 'Ecosystem', 'ecosystem']
target_name:
 Endocrine System
selected_names:
 ['Human Body', 'Operating System', 'A Distributed Computing System']
target_name:
 blood circulation system
selected_names:
 ['Human Body', 'Water pipe system', 'River']
target_name:
 cell
selected_names:
 ['communication networks', 'Factory System', 'A Distributed Computing System']
target_name:
 cell
selected_names:
 ['Evolution', 'communication networks', 'Heart']
target_name:
 Human body
selected_names:
 ['Human Body', 'Human Hands', 'Heart']
target_name:
 Brain system
selected_names:
 ['The Brain', 'How the Human Brain Works', 'Neural Networks']
target_name:
 Hematopoietic System
selected_names:
 ['Human Body', 'ecosystem', 'A Distributed Computing System']
Processed 50/400
target_name:
 Cellular Structure
selected_names:
 ['Building Structure', 'Architecture', 'Building']
target_name:
 DNA replication
selected_names:
 ['code', 'the replicator', 'Baking']
target_name:
 blood circulation system
selected_names:
 ['air circulation ducts', 'Water pipe system', 'River']
target_name:
 Protein
selected_names:
 ['Recipes', 'Computer Code', 'Buildings']
target_name:
 cell
selected_names:
 ['communication networks', 'Factory System', 'A Distributed Computing System']
target_name:
 Genes
selected_names:
 ['Computer Code', 'Machines', 'Factory System']
target_name:
 The Evolution of Viruses
selected_names:
 ['Evolution', 'bacterial mutation', 'natural selection']
target_name:
 Immune System
selected_names:
 ['Human Body', 'Firewall', 'Disease']
target_name:
 Transcription and Translation
selected_names:
 ['Translation', 'Deciphering the Code', 'Computer Code']
target_name:
 forest
selected_names:
 ['forest', 'Ecosystem', 'ecosystem']
Processed 60/400
target_name:
 virus
selected_names:
 ['code', 'illness', 'bacterial mutation']
target_name:
 artificial selection
selected_names:
 ['natural selection', 'Biological Evolution', 'bacterial mutation']
target_name:
 slot machine
selected_names:
 ['Dominoes', 'Machines', 'A Pinball Game']
target_name:
 Migraines
selected_names:
 ['illness', 'The Brain', 'Drug Treatment']
target_name:
 Sperm Motility
selected_names:
 ['Robotic Movement', 'atom', 'pendulum motion']
target_name:
 Prostate
selected_names:
 ['Human Body', 'Disease', 'Car']
target_name:
 Skeletal System
selected_names:
 ['the skeletal system', 'Building Structure', 'Architecture']
target_name:
 Blood sugar regulation
selected_names:
 ['electronic scale automatically adjusts', 'Financial Balance', 'Financial Equilibrium']
target_name:
 Reproductive System
selected_names:
 ['Factory System', 'Plants', "the factory's production line"]
target_name:
 immune desert
selected_names:
 ['Desert', 'Dust Storm', 'Skin System']
Processed 70/400
target_name:
 microRNA
selected_names:
 ['code', 'Regulator', 'air filter']
target_name:
 Cytokine Storm
selected_names:
 ['Dust Storm', 'Crowd', 'Urban Entropy Increase']
target_name:
 Alveoli
selected_names:
 ['air circulation ducts', 'Balloons', 'sponge']
target_name:
 Respiratory system
selected_names:
 ['Air handling system', 'air circulation ducts', 'lubrication system']
target_name:
 Nasal cavity
selected_names:
 ['air filter', 'Air handling system', 'air circulation ducts']
target_name:
 Digestive System
selected_names:
 ['Human Body', 'Air handling system', 'Cooking']
target_name:
 Macrophages
selected_names:
 ['The Brain', 'Disease', 'Financial Balance']
target_name:
 Disability of the plant
selected_names:
 ['Tree', 'Disease', 'Circuit Malfunction']
target_name:
 Immunological Memory
selected_names:
 ['knowledge', 'memory', 'The Brain']
target_name:
 Immunity and Immunity
selected_names:
 ['illness', 'Firewall', 'Human Body']
Processed 80/400
target_name:
 Immune Tolerance
selected_names:
 ['cocoon', 'Deafness', 'Blindness']
target_name:
 Immune Tolerance
selected_names:
 ['cocoon', 'Deafness', 'Blindness']
target_name:
 deaf
selected_names:
 ['Deafness', 'sound system', 'blind']
target_name:
 Blood Chest Barrier
selected_names:
 ['Human Body', 'Walls', 'The Great Wall']
target_name:
 Limit Modification System
selected_names:
 ['program', 'Immunity', 'password lock']
target_name:
 Rod of Asclepius
selected_names:
 ['Healing', 'Ancient Greece', 'illness']
target_name:
 Healthcare
selected_names:
 ['illness', 'Human Body', 'education']
target_name:
 Air Pollution
selected_names:
 ['Car', 'Burning Energy', 'Urban']
target_name:
 The Periodic Table
selected_names:
 ['Biological Evolution', 'atom', 'Molecular Symmetry']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
Processed 90/400
target_name:
 Molecular Synthesis
selected_names:
 ['Chemical Reactions', 'Molecular Symmetry', 'bacterial mutation']
target_name:
 Chemical Separation
selected_names:
 ['sponge', 'Factory', 'Disassembly']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'atom', 'Cooking']
target_name:
 Electrochemical Reaction
selected_names:
 ['Circuits', 'Electronic Signal Transmission', 'atom']
target_name:
 Crystals
selected_names:
 ['The Puzzle', 'Mirrors', 'A Puzzle']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'atom']
target_name:
 Chemical Reaction
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'Friction']
target_name:
 Periodic Table
selected_names:
 ['book', 'Bookshelf', 'Chemical Reactions']
Processed 100/400
target_name:
 Chemical Analysis
selected_names:
 ['Chemical Reactions', 'Mathematical Calculations', 'Prospecting']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 chemical element
selected_names:
 ['atom', 'Reactor', 'gas molecules']
target_name:
 Chemical reaction
selected_names:
 ['Chemical Reactions', 'Reactor', 'Burning Energy']
target_name:
 Chemical Reaction
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'gas molecules']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'atom']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 Chemical Substances
selected_names:
 ['Chemical Reactions', 'sponge', 'Buildings']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 Chemical Reaction
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'Friction']
Processed 110/400
target_name:
 Chemical Reactions
selected_names:
 ['Chemical Reactions', 'Factory', 'Cooking']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'atom']
target_name:
 Chemical Reaction
selected_names:
 ['Chemical Reactions', 'Burning Energy', 'gas molecules']
target_name:
 Chemistry
selected_names:
 ['Chemical Reactions', 'Cooking', 'gas molecules']
target_name:
 Chiral Molecules
selected_names:
 ['Molecular Symmetry', 'Chemical Reactions', 'The Helix Bridge']
target_name:
 Amphiphile
selected_names:
 ['sponge', 'Molecular Symmetry', 'atom']
target_name:
 Enantiomers
selected_names:
 ['Mirrors', 'Human Hands', '3D Projection']
target_name:
 Functional Group
selected_names:
 ['Group Behavior', 'ecosystem', 'Occupation']
target_name:
 Polymer Synthesis
selected_names:
 ['Chemical Reactions', 'Manual', 'The Production Line of a Car Factory']
target_name:
 Polymer Structure
selected_names:
 ['Building Structure', 'Architecture', 'a three-dimensional puzzle']
Processed 120/400
target_name:
 High Molecular Polymers
selected_names:
 ['Chemical Reactions', 'Molecular Symmetry', 'Manual']
target_name:
 Polymer Composites
selected_names:
 ['Buildings', 'Architecture', 'Chemical Reactions']
target_name:
 Polymer Surface Modification
selected_names:
 ['Chemical Reactions', 'Makeup', 'Sun Protection']
target_name:
 The Swarm
selected_names:
 ['Vortex', 'Crowd', 'Foundation Series']
target_name:
 The Brain
selected_names:
 ['How the Human Brain Works', 'The Nervous System', 'Neural Networks']
target_name:
 Deep Learning
selected_names:
 ['Neural Networks', 'The Brain', 'The Nervous System']
target_name:
 Deep Learning
selected_names:
 ['Neural Networks', 'The Brain', 'The Nervous System']
target_name:
 Computer Networks
selected_names:
 ['communication networks', 'Neural Networks', 'Information Flow']
target_name:
 Computer Systems
selected_names:
 ['Machines', 'A Distributed Computing System', 'Factory System']
target_name:
 Artificial Intelligence
selected_names:
 ['mind', 'The Brain', 'How the Human Brain Works']
Processed 130/400
target_name:
 Computer
selected_names:
 ['Computer', 'Machines', 'The Neural Network of Computers']
target_name:
 Memory
selected_names:
 ['memory', 'The Brain', 'Operating System']
target_name:
 hard drive
selected_names:
 ['memory', 'File Cabinet', 'Rental Housing']
target_name:
 Network
selected_names:
 ['communication networks', 'Information Flow', 'The Neural Network of Computers']
target_name:
 programming
selected_names:
 ['Computer Code', 'CPU', 'Computer']
target_name:
 Database
selected_names:
 ['File Cabinet', 'A Distributed Computing System', 'Machines']
target_name:
 Encryption
selected_names:
 ['Deciphering the Code', 'password lock', 'Lock']
target_name:
 Internet Security
selected_names:
 ['Firewall', 'Rental Housing', 'Information Flow']
target_name:
 cache
selected_names:
 ['memory', 'knowledge', 'File Cabinet']
target_name:
 Program Code
selected_names:
 ['Computer Code', 'Deciphering the Code', 'Computer']
Processed 140/400
target_name:
 Version Control
selected_names:
 ['Ledger', 'Bookshelf', 'File Cabinet']
target_name:
 Cloud Computing
selected_names:
 ['A Distributed Computing System', 'Rental Housing', 'communication networks']
target_name:
 Software Development
selected_names:
 ['Computer Code', 'Machines', 'Operating System']
target_name:
 computer
selected_names:
 ['CPU', 'Computer', 'Computer Code']
target_name:
 Metaverse
selected_names:
 ['Brave New World', 'Urban', 'universe']
target_name:
 Feature Engineering
selected_names:
 ['Miner', 'Prospecting', 'Cooking']
target_name:
 Bias-Variance Equilibrium
selected_names:
 ['Financial Equilibrium', 'Financial Balance', 'The Law of Means']
target_name:
 Cross Validation
selected_names:
 ['Blankets', 'Investors', 'competition']
target_name:
 random forest
selected_names:
 ['forest', 'Miner', 'Pedigree Trees']
target_name:
 Mining Association Rules
selected_names:
 ['Prospecting', 'shelf', 'Ledger']
Processed 150/400
target_name:
 PCA Dimensionality Reduction Algorithm
selected_names:
 ['3D Projection', 'Miner', 'a three-dimensional puzzle']
target_name:
 KNN Algorithm
selected_names:
 ['Finding Nearest Neighbors', 'Crowd', 'Social Circle']
target_name:
 Bayesian Algorithms
selected_names:
 ['The Law of Means', 'Miner', 'Taylor Expansion']
target_name:
 AdaBoost Algorithm
selected_names:
 ['Taylor Expansion', 'Miner', 'Program Error']
target_name:
 Neuroevolutionary Algorithms
selected_names:
 ['Evolution', 'The Brain', 'The Neural Network of Computers']
target_name:
 EM Algorithm
selected_names:
 ['A Distributed Computing System', 'Miner', 'The Neural Network of Computers']
target_name:
 GAN Algorithm
selected_names:
 ['The Neural Network of Computers', 'Neural Networks', 'Computer Code']
target_name:
 Ensemble Learning Algorithms
selected_names:
 ['Neural Networks', 'Families', 'Group Behavior']
target_name:
 Bagging Algorithms
selected_names:
 ['Blankets', 'The Puzzle', 'Warehouse']
target_name:
 EM Algorithm
selected_names:
 ['A Distributed Computing System', 'Miner', 'The Neural Network of Computers']
Processed 160/400
target_name:
 Greedy algorithm
selected_names:
 ['The Maze Problem', 'find a shortest path on the map', 'Checkers']
target_name:
 Hierarchical Clustering Algorithms
selected_names:
 ['Pedigree Trees', 'Feudal Dynasties', 'Families']
target_name:
 Blockchain
selected_names:
 ['Ledger', 'communication networks', 'Computer Code']
target_name:
 Internet of Things
selected_names:
 ['A Distributed Computing System', 'communication networks', 'Rental Housing']
target_name:
 Internet
selected_names:
 ['communication networks', 'Information Flow', 'Expressway']
target_name:
 Database
selected_names:
 ['File Cabinet', 'memory', "the factory's production line"]
target_name:
 Monetary Policy
selected_names:
 ['Financial Markets', 'Financial Balance', 'Financial Equilibrium']
target_name:
 Stock Market
selected_names:
 ['Financial Markets', 'Buy and Sell', 'Horse Racing']
target_name:
 Asset Pricing
selected_names:
 ['Financial Markets', 'money', 'Insurance Contract']
target_name:
 Option Pricing Model
selected_names:
 ['Financial Markets', 'Insurance Contract', 'Principle of Financial Balance']
Processed 170/400
target_name:
 Portfolio
selected_names:
 ['Investors', 'Financial Markets', 'money']
target_name:
 Marketing
selected_names:
 ['Supply Chain', 'Buy and Sell', 'business']
target_name:
 Economics
selected_names:
 ['Financial Equilibrium', 'business', 'money']
target_name:
 Business cycle
selected_names:
 ['business', 'money', 'Financial Equilibrium']
target_name:
 Earth's Plate Movement
selected_names:
 ['planet', 'Population Movement', 'Seismic Imaging']
target_name:
 Earth's Atmosphere
selected_names:
 ['Greenhouse', 'Greenhouses', 'air filter']
target_name:
 Volcanic Eruption
selected_names:
 ['Burning Energy', 'Spread of Fire', 'Dust Storm']
target_name:
 Atmosphere
selected_names:
 ['Greenhouse', 'gas molecules', 'planet']
target_name:
 Glacier
selected_names:
 ['Ice Cream', 'River', 'object slides']
target_name:
 Tide
selected_names:
 ['tidal phenomena', 'Water Wave Propagation', 'pendulum motion']
Processed 180/400
target_name:
 Active faults
selected_names:
 ['Circuit Malfunction', 'object slides', 'Vehicle Traffic']
target_name:
 Active Fault
selected_names:
 ['Circuit Malfunction', 'object slides', 'Program Error']
target_name:
 Geological folds
selected_names:
 ['Origami', 'Blankets', 'wrinkles']
target_name:
 Volcano
selected_names:
 ['Burning Energy', 'Power Generation', 'Car']
target_name:
 Rock Metamorphosis
selected_names:
 ['Evolution', 'Biological Evolution', 'bacterial mutation']
target_name:
 Geological Formation
selected_names:
 ['Buildings', 'Building Structure', 'Factory System']
target_name:
 Deposit Formation
selected_names:
 ['Financial Balance', 'Principle of Financial Balance', 'File Cabinet']
target_name:
 Empire
selected_names:
 ['Ancient Rome', 'Ancient Western Asia', 'Ancient Greece']
target_name:
 American Congressional System
selected_names:
 ['Mexican Political System', 'Chinese Political System', 'nation']
target_name:
 British Parliamentary System
selected_names:
 ['Australian Parliamentary System', 'Mexican Political System', 'Chinese Political System']
Processed 190/400
target_name:
 Russian Political System
selected_names:
 ['Chinese Political System', 'Australian Parliamentary System', 'Mexican Political System']
target_name:
 Spanish Political System
selected_names:
 ['Mexican Political System', 'Australian Parliamentary System', 'German Constitutional Monarchy']
target_name:
 Japanese Government System
selected_names:
 ['British Government System', 'Australian Parliamentary System', 'government']
target_name:
 Reign of the Pharaohs
selected_names:
 ['Feudal Dynasties', 'Ancient Western Asia', 'Ancient Greece']
target_name:
 Pyramids
selected_names:
 ['Feudal Dynasties', 'Buildings', 'Building']
target_name:
 Napoleonic Wars
selected_names:
 ['American Civil War', 'The French Revolution', 'Enlightenment']
target_name:

,id,target,target_background,gold_source,top_10_sources,top_10_scores,llm_selected_sources,llm_selected_scores,gold_rank,embedding_mode,baseline
0,1,biological clock,The biological clock is a fundamental aspect o...,clock,"[Biological Evolution, clock, bacterial mutati...","[0.3786787182861502, 0.37565001052459696, 0.31...","[clock, day and night cycle, Time Machine]","[0.37565001052459696, 0.29895759869257044, 0.2...",1,name_properties,embedding_llm_top10_to_3
1,2,Biosphere,The biosphere refers to the sum of all ecosyst...,Library,"[Ecosystem, ecosystem, Biological Evolution, C...","[0.5644059383971753, 0.5044757153365504, 0.355...","[Ecosystem, ecosystem, Desert]","[0.5644059383971753, 0.5044757153365504, 0.341...",-1,name_properties,embedding_llm_top10_to_3
2,3,Respiratory system,The respiratory system is a critical biologica...,engine,"[respiration, Air handling system, Human Body,...","[0.4439990903135665, 0.40105959603856384, 0.39...","[Air handling system, air circulation ducts, l...","[0.40105959603856384, 0.3127274941224897, 0.29...",-1,name_properties,embedding_llm_top10_to_3
3,4,Spread of Pathogens,"The spread of pathogens is a serious concern, ...",Spread of Fire,"[Spread of Fire, Disease, Population Movement,...","[0.44654289141485515, 0.43497819694422885, 0.3...","[Spread of Fire, Disease, Population Movement]","[0.44654289141485515, 0.43497819694422885, 0.3...",1,name_properties,embedding_llm_top10_to_3
4,5,Gene editing,Gene editing is a revolutionary technique in m...,kirigami,"[bacterial mutation, edit, Evolution, program,...","[0.3618950292759755, 0.3256726784890958, 0.315...","[bacterial mutation, edit, Evolution]","[0.3618950292759755, 0.3256726784890958, 0.315...",-1,name_properties,embedding_llm_top10_to_3

## Baseline 2b: LLM Selection - Target Name Only

In [24]:
def llm_select_sources_name_only(target_name, candidates, llm_client, top_k=3):
    """Use Llama 405B - Target name only"""
    candidates_text = "\n".join([
        f"{i+1}. {c.name}"
        for i, c in enumerate(candidates)
    ])
    
    prompt = f"""You are selecting analogous sources for a scientific analogy.

Target concept: {target_name}

Candidate source concepts:
{candidates_text}

Select the {top_k} BEST candidates that would make good analogies for the target concept.
Return ONLY a JSON array of the candidate numbers (1-indexed), e.g., [1, 3, 5]
Do not include any explanation, just the JSON array.
"""
    
    try:
        response = llm_client.chat(
            model_name="llama-3.1-405b-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=100
        )
        response_clean = response.strip()
        try:
            selected = json.loads(response_clean)
        except json.JSONDecodeError:
            match = re.search(r'\[[\d,\s]+\]', response_clean)
            if match:
                selected = json.loads(match.group())
            else:
                numbers = re.findall(r'\b([1-9]|10)\b', response_clean)
                selected = [int(n) for n in numbers[:top_k]]
        if not selected:
            return candidates[:top_k]
        return [candidates[i-1] for i in selected if 1 <= i <= len(candidates)][:top_k]
    except Exception as e:
        print(f"LLM selection failed: {e}, falling back to top {top_k}")
        return candidates[:top_k]

# Run Baseline 2b
baseline2b_results = []
print(f"Running Baseline 2b (name only) on {len(df)} examples...")
for idx, row in df.iterrows():
    target_name = row['system_a']
    target_bg = row['system_a_background']
    gold_source = row['system_b']
    
    candidates = finder.find_source(target_name, target_bg, top_k=10)
    selected = llm_select_sources_name_only(target_name, candidates, llm_client, top_k=3)
    
    selected_names = [s.name for s in selected]
    gold_rank = -1
    for i, name in enumerate(selected_names):
        if gold_source.lower() in name.lower() or name.lower() in gold_source.lower():
            gold_rank = i + 1
            break
    
    baseline2b_results.append({
        'id': row['id'],
        'target': target_name,
        'gold_source': gold_source,
        'llm_selected_sources': selected_names,
        'gold_rank': gold_rank,
        'condition': 'name_only'
    })
    
    if (idx + 1) % 50 == 0:
        print(f"Processed {idx + 1}/{len(df)}")

baseline2b_df = pd.DataFrame(baseline2b_results)
baseline2b_df.to_csv('baseline2b_name_only.csv', index=False)
print(f"Baseline 2b saved: {len(baseline2b_df)} rows")

Running Baseline 2b (name only) on 400 examples...
Processed 50/400
Processed 100/400
Processed 150/400
Processed 200/400
Processed 250/400
Processed 300/400
Processed 350/400
Processed 400/400
Baseline 2b saved: 400 rows

## Baseline 2c: LLM Selection - Target Name + Properties + Description

In [25]:
# Build source description lookup
source_desc_lookup = {}
for _, row in df_scar.iterrows():
    source_name = row['system_b']
    if source_name not in source_desc_lookup:
        source_desc_lookup[source_name] = row['system_b_background'] if pd.notna(row['system_b_background']) else ""

def llm_select_sources_full(target_name, target_properties, target_desc, candidates, llm_client, top_k=3):
    """Use Llama 405B - Target name + properties + description"""
    candidates_text = "\n".join([
        f"{i+1}. {c.name} - Properties: {get_source_properties(c.name)} - Description: {source_desc_lookup.get(c.name, '')[:200]}..."
        for i, c in enumerate(candidates)
    ])
    
    prompt = f"""You are selecting analogous sources for a scientific analogy.

Target concept: {target_name}
Target properties: {target_properties}
Target description: {target_desc}

Candidate source concepts:
{candidates_text}

Select the {top_k} BEST candidates that would make good analogies for the target concept.
Return ONLY a JSON array of the candidate numbers (1-indexed), e.g., [1, 3, 5]
Do not include any explanation, just the JSON array.
"""
    
    try:
        response = llm_client.chat(
            model_name="llama-3.1-405b-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=100
        )
        response_clean = response.strip()
        try:
            selected = json.loads(response_clean)
        except json.JSONDecodeError:
            match = re.search(r'\[[\d,\s]+\]', response_clean)
            if match:
                selected = json.loads(match.group())
            else:
                numbers = re.findall(r'\b([1-9]|10)\b', response_clean)
                selected = [int(n) for n in numbers[:top_k]]
        if not selected:
            return candidates[:top_k]
        return [candidates[i-1] for i in selected if 1 <= i <= len(candidates)][:top_k]
    except Exception as e:
        print(f"LLM selection failed: {e}, falling back to top {top_k}")
        return candidates[:top_k]

# Run Baseline 2c
baseline2c_results = []
print(f"Running Baseline 2c (name + properties + description) on {len(df)} examples...")
for idx, row in df.iterrows():
    target_name = row['system_a']
    target_bg = row['system_a_background']
    target_properties = get_target_properties(row)
    gold_source = row['system_b']
    
    candidates = finder.find_source(target_name, target_bg, top_k=10)
    selected = llm_select_sources_full(target_name, target_properties, target_bg, candidates, llm_client, top_k=3)
    
    selected_names = [s.name for s in selected]
    gold_rank = -1
    for i, name in enumerate(selected_names):
        if gold_source.lower() in name.lower() or name.lower() in gold_source.lower():
            gold_rank = i + 1
            break
    
    baseline2c_results.append({
        'id': row['id'],
        'target': target_name,
        'gold_source': gold_source,
        'llm_selected_sources': selected_names,
        'gold_rank': gold_rank,
        'condition': 'name_properties_description'
    })
    
    if (idx + 1) % 50 == 0:
        print(f"Processed {idx + 1}/{len(df)}")

baseline2c_df = pd.DataFrame(baseline2c_results)
baseline2c_df.to_csv('baseline2c_full.csv', index=False)
print(f"Baseline 2c saved: {len(baseline2c_df)} rows")

Running Baseline 2c (name + properties + description) on 400 examples...
Processed 50/400
Processed 100/400
Processed 150/400
Processed 200/400
Processed 250/400
Processed 300/400
Processed 350/400
Processed 400/400
Baseline 2c saved: 400 rows

## Baseline 2d: LLM Selection - Target Name + Description

In [26]:
def llm_select_sources_name_desc(target_name, target_desc, candidates, llm_client, top_k=3):
    """Use Llama 405B - Target name + description"""
    candidates_text = "\n".join([
        f"{i+1}. {c.name} - Description: {source_desc_lookup.get(c.name, '')[:200]}..."
        for i, c in enumerate(candidates)
    ])
    
    prompt = f"""You are selecting analogous sources for a scientific analogy.

Target concept: {target_name}
Target description: {target_desc}

Candidate source concepts:
{candidates_text}

Select the {top_k} BEST candidates that would make good analogies for the target concept.
Return ONLY a JSON array of the candidate numbers (1-indexed), e.g., [1, 3, 5]
Do not include any explanation, just the JSON array.
"""
    
    try:
        response = llm_client.chat(
            model_name="llama-3.1-405b-instruct",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=100
        )
        response_clean = response.strip()
        try:
            selected = json.loads(response_clean)
        except json.JSONDecodeError:
            match = re.search(r'\[[\d,\s]+\]', response_clean)
            if match:
                selected = json.loads(match.group())
            else:
                numbers = re.findall(r'\b([1-9]|10)\b', response_clean)
                selected = [int(n) for n in numbers[:top_k]]
        if not selected:
            return candidates[:top_k]
        return [candidates[i-1] for i in selected if 1 <= i <= len(candidates)][:top_k]
    except Exception as e:
        print(f"LLM selection failed: {e}, falling back to top {top_k}")
        return candidates[:top_k]

# Run Baseline 2d
baseline2d_results = []
print(f"Running Baseline 2d (name + description) on {len(df)} examples...")
for idx, row in df.iterrows():
    target_name = row['system_a']
    target_bg = row['system_a_background']
    gold_source = row['system_b']
    
    candidates = finder.find_source(target_name, target_bg, top_k=10)
    selected = llm_select_sources_name_desc(target_name, target_bg, candidates, llm_client, top_k=3)
    
    selected_names = [s.name for s in selected]
    gold_rank = -1
    for i, name in enumerate(selected_names):
        if gold_source.lower() in name.lower() or name.lower() in gold_source.lower():
            gold_rank = i + 1
            break
    
    baseline2d_results.append({
        'id': row['id'],
        'target': target_name,
        'gold_source': gold_source,
        'llm_selected_sources': selected_names,
        'gold_rank': gold_rank,
        'condition': 'name_description'
    })
    
    if (idx + 1) % 50 == 0:
        print(f"Processed {idx + 1}/{len(df)}")

baseline2d_df = pd.DataFrame(baseline2d_results)
baseline2d_df.to_csv('baseline2d_name_desc.csv', index=False)
print(f"Baseline 2d saved: {len(baseline2d_df)} rows")

Running Baseline 2d (name + description) on 400 examples...
Processed 50/400
Processed 100/400
Processed 150/400
Processed 200/400
Processed 250/400
Processed 300/400
Processed 350/400
Processed 400/400
Baseline 2d saved: 400 rows

## Summary Statistics

In [27]:
# Compare all baselines
print("=" * 60)
print("BASELINE COMPARISON")
print("=" * 60)

results_summary = []

# Baseline 1 metrics
b1_found = (baseline1_results['gold_rank'] > 0).sum()
b1_total = len(baseline1_results)
b1_mean = baseline1_results[baseline1_results['gold_rank'] > 0]['gold_rank'].mean()
print(f"\nBaseline 1 (Embedding Top 3):")
print(f"  Gold found: {b1_found}/{b1_total} ({100*b1_found/b1_total:.1f}%)")
print(f"  Mean gold rank (when found): {b1_mean:.2f}")
results_summary.append({'baseline': 'Embedding Top 3', 'found': b1_found, 'total': b1_total, 'hit_rate': 100*b1_found/b1_total, 'mean_rank': b1_mean})

# Baseline 2 metrics (properties only)
b2_found = (baseline2_df['gold_rank'] > 0).sum()
b2_total = len(baseline2_df)
b2_mean = baseline2_df[baseline2_df['gold_rank'] > 0]['gold_rank'].mean()
print(f"\nBaseline 2 (LLM + Properties Only):")
print(f"  Gold found: {b2_found}/{b2_total} ({100*b2_found/b2_total:.1f}%)")
print(f"  Mean gold rank (when found): {b2_mean:.2f}")
results_summary.append({'baseline': 'LLM + Properties Only', 'found': b2_found, 'total': b2_total, 'hit_rate': 100*b2_found/b2_total, 'mean_rank': b2_mean})

# Baseline 2b metrics (name only)
b2b_found = (baseline2b_df['gold_rank'] > 0).sum()
b2b_total = len(baseline2b_df)
b2b_mean = baseline2b_df[baseline2b_df['gold_rank'] > 0]['gold_rank'].mean()
print(f"\nBaseline 2b (LLM + Name Only):")
print(f"  Gold found: {b2b_found}/{b2b_total} ({100*b2b_found/b2b_total:.1f}%)")
print(f"  Mean gold rank (when found): {b2b_mean:.2f}")
results_summary.append({'baseline': 'LLM + Name Only', 'found': b2b_found, 'total': b2b_total, 'hit_rate': 100*b2b_found/b2b_total, 'mean_rank': b2b_mean})

# Baseline 2c metrics (full)
b2c_found = (baseline2c_df['gold_rank'] > 0).sum()
b2c_total = len(baseline2c_df)
b2c_mean = baseline2c_df[baseline2c_df['gold_rank'] > 0]['gold_rank'].mean()
print(f"\nBaseline 2c (LLM + Name + Properties + Description):")
print(f"  Gold found: {b2c_found}/{b2c_total} ({100*b2c_found/b2c_total:.1f}%)")
print(f"  Mean gold rank (when found): {b2c_mean:.2f}")
results_summary.append({'baseline': 'LLM: Name + Props + Desc', 'found': b2c_found, 'total': b2c_total, 'hit_rate': 100*b2c_found/b2c_total, 'mean_rank': b2c_mean})

# Baseline 2d metrics (name + description)
b2d_found = (baseline2d_df['gold_rank'] > 0).sum()
b2d_total = len(baseline2d_df)
b2d_mean = baseline2d_df[baseline2d_df['gold_rank'] > 0]['gold_rank'].mean()
print(f"\nBaseline 2d (LLM + Name + Description):")
print(f"  Gold found: {b2d_found}/{b2d_total} ({100*b2d_found/b2d_total:.1f}%)")
print(f"  Mean gold rank (when found): {b2d_mean:.2f}")
results_summary.append({'baseline': 'LLM: Name + Desc', 'found': b2d_found, 'total': b2d_total, 'hit_rate': 100*b2d_found/b2d_total, 'mean_rank': b2d_mean})

print("\n" + "=" * 60)
summary_df = pd.DataFrame(results_summary)
summary_df.to_csv('baselines_summary.csv', index=False)
print("\nSummary saved to baselines_summary.csv")
summary_df

============================================================
BASELINE COMPARISON
============================================================

Baseline 1 (Embedding Top 3):
  Gold found: 160/400 (40.0%)
  Mean gold rank (when found): 1.75

Baseline 2 (LLM + Properties Only):
  Gold found: 145/400 (36.2%)
  Mean gold rank (when found): 1.66

Baseline 2b (LLM + Name Only):
  Gold found: 129/400 (32.2%)
  Mean gold rank (when found): 1.65

Baseline 2c (LLM + Name + Properties + Description):
  Gold found: 134/400 (33.5%)
  Mean gold rank (when found): 1.55

Baseline 2d (LLM + Name + Description):
  Gold found: 130/400 (32.5%)
  Mean gold rank (when found): 1.62

============================================================

Summary saved to baselines_summary.csv

                   baseline  found  total  hit_rate  mean_rank
0           Embedding Top 3    160    400     40.00   1.750000
1     LLM + Properties Only    145    400     36.25   1.655172
2           LLM + Name Only    129    400     32.25   1.651163
3  LLM: Name + Props + Desc    134    400     33.50   1.552239
4          LLM: Name + Desc    130    400     32.50   1.615385